// +build ignore

// This program generates syscalls.go. It can be invoked by running
// go generate
package main

import (
	"bufio"
	"fmt"
	"html/template"
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

const (
	sys32bitURL = "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/entry/syscalls/syscall_32.tbl"
	sys64bitURL = "https://raw.githubusercontent.com/torvalds/linux/master/arch/x86/entry/syscalls/syscall_64.tbl"
)

func main() {
	var parts []string

	scs64Bit := []string{}
	scs32Bit := []string{}

	// crawl - 64 Bit syscalss
	rsp, err := http.Get(sys64bitURL)
	if err != nil {
		log.Fatal(err)
	}
	defer rsp.Body.Close()

	sc := bufio.NewScanner(rsp.Body)
	for sc.Scan() {
		if !strings.HasPrefix(sc.Text(), "#") {
			parts = strings.Fields(sc.Text())
			if len(parts) > 2 {
				scs64Bit = append(scs64Bit, parts[2])
			}
		}
	}

	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "reading response body:", err)
	}

	// crawl - 32 Bit syscalss
	rsp, err = http.Get(sys32bitURL)
	if err != nil {
		log.Fatal(err)
	}
	defer rsp.Body.Close()

	sc = bufio.NewScanner(rsp.Body)
	for sc.Scan() {
		if !strings.HasPrefix(sc.Text(), "#") {
			parts = strings.Fields(sc.Text())
			if len(parts) > 2 {
				scs32Bit = append(scs32Bit, parts[2])
			}
		}
	}

	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "reading response body:", err)
	}

	f, err := os.Create("syscalls.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	syscallTemplate.Execute(f, struct {
		Timestamp     string
		URL64Bit      string
		URL32Bit      string
		Syscalls64Bit []string
		Syscalls32Bit []string
	}{
		Timestamp:     time.Now().Format("2006-01-02"),
		URL64Bit:      sys64bitURL,
		URL32Bit:      sys32bitURL,
		Syscalls64Bit: scs64Bit,
		Syscalls32Bit: scs32Bit,
	})
}

var syscallTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots on {{ .Timestamp }}
// using data from:
// - {{ .URL64Bit }}
// - {{ .URL32Bit }}

package syscalls

var syscalls64Bit = []string{
{{- range .Syscalls64Bit }}
	"{{ . }}",
{{- end }}
}

var syscalls32Bit = []string{
{{- range .Syscalls32Bit }}
	"{{ . }}",
{{- end }}
}

// IsValid checks if string is a valid 64bit or 32bit linux syscall
func IsValid(syscall string) bool {
	for _, ele := range syscalls64Bit {
		if ele == syscall {
			return true
		}
	}
	for _, ele := range syscalls32Bit {
		if ele == syscall {
			return true
		}
	}
	return false
}
`))
